### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by michael-andreuzza**
Added seven (7) new starter Open Source themes built with Astro, Tailwind CSS and MDX.

### CODE REVIEW

**Comment by Jogai** [comment]
Line 100 has a '(' too much

**Comment by michael-andreuzza** [comment]
> Line 100 has a '(' too much

Fixed. My bad, Sorry

**Review by one-aalam — APPROVED** [review]
Thanks @michael-andreuzza for the addition 👍 (and pardon me for the delay)

**Comment by michael-andreuzza** [comment]
> Thanks @michael-andreuzza for the addition 👍 (and pardon me for the delay)
Thank you too for adding the themes, really appreciate it! :-)

**Pull request merged**
